### ISSUE TITLE
From an API: timedelta code incorrect in your notebook & text

### ISSUE THREAD

**Issue by Hymenopteran** [stefmolin/Hands-On-Data-Analysis-with-Pandas#3]
you wrote: 
`yesterday = datetime.date.today() - datetime.timedelta(days=1)`

which gives:
_AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'_

should be:
`yesterday = datetime.today() - timedelta(days=1)`

and also:
`'starttime': yesterday-timedelta(days=26)`

**Comment by stefmolin** [comment]
The code is correct as is. Going off the error and your code, it looks like you imported:
```
from datetime import *
```
This is bad practice. If you restart the notebook and run the import statement in the cell, it will work as expected:
```
import datetime
```
